/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.suisse.server.log.report;

import org.junit.Test;
import static org.junit.Assert.*;

public class LogReportTest {
    @Test public void testSomeLibraryMethod() {
        LogReport classUnderTest = new LogReport();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
